import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express from "express";
import { z } from "zod";
import fs from "fs/promises";
import path from "path";
import os from "os";
import { exec } from "child_process";
import { promisify } from "util";
import { runCodingAgent, parseSummary } from "./agent.js";

const execAsync = promisify(exec);
const app = express();
app.use(express.json());

function parseRepoUrl(url) {
  const match = url.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
  if (!match) throw new Error(`Cannot parse GitHub repo URL: ${url}`);
  return { owner: match[1], repo: match[2].replace(/\.git$/, "") };
}

function slugify(text) {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 40);
  return slug || Math.random().toString(36).slice(2, 8);
}

function extractTitle(summary) {
  for (const line of summary.split("\n").map((l) => l.trim()).filter(Boolean)) {
    const clean = line.replace(/^[#*\->]+\s*/, "").replace(/\*\*/g, "").replace(/`/g, "");
    if (clean.length > 5) return clean.slice(0, 72);
  }
  return summary.slice(0, 72);
}

async function hasChanges(workDir) {
  const { stdout } = await execAsync("git status --porcelain", { cwd: workDir });
  return stdout.trim().length > 0;
}

function createServer() {
  const server = new McpServer({ name: "front", version: "1.0.0" });

  server.tool(
    "implement_and_pr",
    "프롬프트를 받아 GitHub 저장소 코드를 자동으로 수정하고 PR을 생성합니다",
    {
      prompt: z.string().describe("구현할 기능 또는 수정 사항 설명"),
    },
    async ({ prompt }, extra) => {
      const sendLog = async (msg) => {
        process.stderr.write(`[front-agent] ${msg}\n`);
        try {
          await extra.sendNotification({
            method: "notifications/message",
            params: { level: "info", logger: "front-agent", data: msg },
          });
        } catch {}
      };

      const repo_url = process.env.GITHUB_REPO_URL;
      const base_branch = "develop";
      const token = process.env.GITHUB_TOKEN;
      if (!token) return { content: [{ type: "text", text: "Error: GITHUB_TOKEN이 설정되지 않았습니다." }] };
      if (!repo_url) return { content: [{ type: "text", text: "Error: GITHUB_REPO_URL이 설정되지 않았습니다." }] };

      const { owner, repo } = parseRepoUrl(repo_url);
      const authedUrl = `https://${token}@github.com/${owner}/${repo}.git`;

      const now = new Date();
      const datePart = now.toISOString().slice(0, 16).replace(/[-T:]/g, "").slice(0, 12);
      const branchName = `agent/${datePart}-${slugify(prompt)}`;

      const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "front-agent-"));

      try {
        // 1. Clone
        await sendLog(`📦 저장소 클론 중... (${owner}/${repo}@${base_branch})`);
        await execAsync(`git clone --depth=1 --branch ${base_branch} ${authedUrl} .`, {
          cwd: tmpDir,
        });

        // Configure git identity for commits
        await execAsync('git config user.email "agent@rorr.club"', { cwd: tmpDir });
        await execAsync('git config user.name "front-agent"', { cwd: tmpDir });

        // 2. Create new branch
        await sendLog(`🌿 브랜치 생성: ${branchName}`);
        await execAsync(`git checkout -b ${branchName}`, { cwd: tmpDir });

        // 3. Run Claude coding agent
        await sendLog(`🤖 Claude 에이전트 실행 중... (프롬프트: "${prompt.slice(0, 60)}")`);
        const raw = await runCodingAgent(prompt, tmpDir, sendLog);
        const { title: agentTitle, summary } = parseSummary(raw);
        await sendLog("✅ Claude 에이전트 완료");

        // 4. Check if anything changed
        if (!(await hasChanges(tmpDir))) {
          return {
            content: [{
              type: "text",
              text: `에이전트가 실행됐지만 변경된 파일이 없습니다.\n\n${summary}`,
            }],
          };
        }

        // 5. Commit & push
        await sendLog("💾 변경사항 커밋 & 푸시 중...");
        await execAsync("git add -A", { cwd: tmpDir });
        await execAsync(
          `git commit -m "feat: ${prompt.slice(0, 60).replace(/"/g, "'")}\n\nGenerated by front-agent"`,
          { cwd: tmpDir }
        );
        await execAsync(`git push origin ${branchName}`, { cwd: tmpDir });

        // 6. Create PR via GitHub API
        await sendLog("🔗 PR 생성 중...");
        const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json",
            Accept: "application/vnd.github.v3+json",
          },
          body: JSON.stringify({
            title: agentTitle || extractTitle(summary),
            body: `## Summary\n\n${summary}\n\n---\n*🤖 Generated by front-agent*`,
            head: branchName,
            base: base_branch,
          }),
        });

        const pr = await prRes.json();

        if (!prRes.ok) {
          throw new Error(`GitHub API error: ${JSON.stringify(pr)}`);
        }

        await sendLog(`🎉 PR 생성 완료! ${pr.html_url}`);
        return {
          content: [{
            type: "text",
            text: `✅ PR 생성 완료!\n\nURL: ${pr.html_url}\n브랜치: ${branchName}\n\n## 변경 내용\n${summary}`,
          }],
        };
      } finally {
        await fs.rm(tmpDir, { recursive: true, force: true });
      }
    }
  );

  server.tool(
    "design_ui",
    "기능 요구사항 기반으로 UI/화면 설계를 제안합니다",
    {
      feature: z.string().describe("구현할 기능 설명"),
      constraints: z.string().optional().describe("제약 조건(디자인 시스템, 플랫폼, 기술 스택 등)"),
    },
    async ({ feature, constraints }) => ({
      content: [
        {
          type: "text",
          text: [
            `[front] "${feature}" UI 설계`,
            constraints ? `제약: ${constraints}` : undefined,
            "",
            "- 화면/플로우, 주요 컴포넌트, 상태/에러/로딩 처리를 포함한 설계안을 반환합니다.",
          ]
            .filter(Boolean)
            .join("\n"),
        },
      ],
    })
  );

  server.tool(
    "review_component",
    "컴포넌트 코드/구조를 리뷰하고 개선안을 제안합니다",
    {
      code: z.string().describe("리뷰할 코드 또는 핵심 발췌"),
      focus: z
        .string()
        .optional()
        .describe("집중할 포인트(접근성, 상태 관리, 성능, 아키텍처, 테스트 등)"),
    },
    async ({ code, focus }) => ({
      content: [
        {
          type: "text",
          text: [
            "[front] 컴포넌트 리뷰",
            focus ? `포커스: ${focus}` : undefined,
            "",
            "입력 코드:",
            code,
          ]
            .filter(Boolean)
            .join("\n"),
        },
      ],
    })
  );

  return server;
}

app.post("/mcp", async (req, res) => {
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
  const server = createServer();
  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
  await server.close();
});

app.get("/health", (_, res) => res.json({ status: "ok", server: "front" }));

app.listen(5004, () => process.stdout.write("front MCP server running on :5004\n"));
