import "dotenv/config";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StreamableHTTPServerTransport } from "@modelcontextprotocol/sdk/server/streamableHttp.js";
import express from "express";
import { z } from "zod";
import fs from "fs/promises";
import path from "path";
import os from "os";
import { exec } from "child_process";
import { promisify } from "util";
import { randomUUID } from "crypto";
import { runCodingAgent, parseSummary } from "./agent.js";

const execAsync = promisify(exec);
const app = express();
app.use(express.json());

// job store: jobId -> { status, prompt, logs, result, error, createdAt }
const jobs = new Map();
// dedup: prompt -> jobId (only while running)
const runningByPrompt = new Map();

function parseRepoUrl(url) {
  const match = url.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
  if (!match) throw new Error(`Cannot parse GitHub repo URL: ${url}`);
  return { owner: match[1], repo: match[2].replace(/\.git$/, "") };
}

function slugify(text) {
  const slug = text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .slice(0, 40);
  return slug || Math.random().toString(36).slice(2, 8);
}

function extractTitle(summary) {
  for (const line of summary.split("\n").map((l) => l.trim()).filter(Boolean)) {
    const clean = line.replace(/^[#*\->]+\s*/, "").replace(/\*\*/g, "").replace(/`/g, "");
    if (clean.length > 5) return clean.slice(0, 72);
  }
  return summary.slice(0, 72);
}

async function hasChanges(workDir) {
  const { stdout } = await execAsync("git status --porcelain", { cwd: workDir });
  return stdout.trim().length > 0;
}

async function executeJob(jobId, prompt) {
  const job = jobs.get(jobId);
  const pushLog = (msg) => {
    process.stderr.write(`[front-agent][${jobId}] ${msg}\n`);
    job.logs.push(msg);
  };

  const repo_url = process.env.GITHUB_REPO_URL;
  const base_branch = "develop";
  const token = process.env.GITHUB_TOKEN;

  if (!token) { job.status = "error"; job.error = "GITHUB_TOKEN이 설정되지 않았습니다."; return; }
  if (!repo_url) { job.status = "error"; job.error = "GITHUB_REPO_URL이 설정되지 않았습니다."; return; }

  const { owner, repo } = parseRepoUrl(repo_url);
  const authedUrl = `https://${token}@github.com/${owner}/${repo}.git`;

  const now = new Date();
  const datePart = now.toISOString().slice(0, 16).replace(/[-T:]/g, "").slice(0, 12);
  const branchName = `agent/${datePart}-${slugify(prompt)}`;

  const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "front-agent-"));

  try {
    pushLog(`📦 저장소 클론 중... (${owner}/${repo}@${base_branch})`);
    await execAsync(`git clone --depth=1 --branch ${base_branch} ${authedUrl} .`, { cwd: tmpDir });
    await execAsync('git config user.email "agent@rorr.club"', { cwd: tmpDir });
    await execAsync('git config user.name "front-agent"', { cwd: tmpDir });

    pushLog(`🌿 브랜치 생성: ${branchName}`);
    await execAsync(`git checkout -b ${branchName}`, { cwd: tmpDir });

    pushLog(`🤖 Claude 에이전트 실행 중... (프롬프트: "${prompt.slice(0, 60)}")`);
    const heartbeat = setInterval(() => pushLog("⏳ 작업 진행 중..."), 15000);
    let raw;
    try {
      raw = await runCodingAgent(prompt, tmpDir, pushLog);
    } finally {
      clearInterval(heartbeat);
    }
    const { title: agentTitle, summary } = parseSummary(raw);
    pushLog("✅ Claude 에이전트 완료");

    if (!(await hasChanges(tmpDir))) {
      job.status = "done";
      job.result = { text: `에이전트가 실행됐지만 변경된 파일이 없습니다.\n\n${summary}` };
      return;
    }

    pushLog("💾 변경사항 커밋 & 푸시 중...");
    await execAsync("git add -A", { cwd: tmpDir });
    await execAsync(
      `git commit -m "feat: ${prompt.slice(0, 60).replace(/"/g, "'")}\n\nGenerated by front-agent"`,
      { cwd: tmpDir }
    );
    await execAsync(`git push origin ${branchName}`, { cwd: tmpDir });

    pushLog("🔗 PR 생성 중...");
    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
        Accept: "application/vnd.github.v3+json",
      },
      body: JSON.stringify({
        title: agentTitle || extractTitle(summary),
        body: `## Summary\n\n${summary}\n\n---\n*🤖 Generated by front-agent*`,
        head: branchName,
        base: base_branch,
      }),
    });

    const pr = await prRes.json();
    if (!prRes.ok) throw new Error(`GitHub API error: ${JSON.stringify(pr)}`);

    pushLog(`🎉 PR 생성 완료! ${pr.html_url}`);
    job.status = "done";
    job.result = {
      text: `✅ PR 생성 완료!\n\nURL: ${pr.html_url}\n브랜치: ${branchName}\n\n## 변경 내용\n${summary}`,
      pr_url: pr.html_url,
      branch: branchName,
    };
  } catch (err) {
    pushLog(`❌ 오류: ${err.message}`);
    job.status = "error";
    job.error = err.message;
  } finally {
    runningByPrompt.delete(prompt.trim());
    await fs.rm(tmpDir, { recursive: true, force: true });
  }
}

function createServer() {
  const server = new McpServer({ name: "front", version: "1.0.0" });

  server.tool(
    "run",
    "프롬프트를 받아 GitHub 저장소 코드를 자동으로 수정하고 PR을 생성합니다. 즉시 job_id를 반환하며, status 툴로 진행 상황을 확인하세요.",
    { prompt: z.string().describe("실행할 프롬프트") },
    async ({ prompt }) => {
      const key = prompt.trim();

      // 동일 프롬프트가 이미 실행 중이면 기존 job ID 반환
      if (runningByPrompt.has(key)) {
        const existingId = runningByPrompt.get(key);
        return {
          content: [{
            type: "text",
            text: `⏳ 동일한 작업이 이미 진행 중입니다.\n\njob_id: ${existingId}\n\nstatus 툴로 진행 상황을 확인하세요.`,
          }],
        };
      }

      const jobId = randomUUID();
      jobs.set(jobId, {
        status: "running",
        prompt: key,
        logs: [],
        result: null,
        error: null,
        createdAt: new Date().toISOString(),
      });
      runningByPrompt.set(key, jobId);

      // 백그라운드 실행 (await 하지 않음)
      executeJob(jobId, key).catch(() => {});

      return {
        content: [{
          type: "text",
          text: `🚀 작업이 시작됐습니다.\n\njob_id: ${jobId}\n\nstatus 툴로 진행 상황을 확인하세요.`,
        }],
      };
    }
  );

  server.tool(
    "status",
    "run 툴로 시작한 작업의 진행 상황과 결과를 확인합니다.",
    { job_id: z.string().describe("run 툴이 반환한 job_id") },
    async ({ job_id }) => {
      const job = jobs.get(job_id);
      if (!job) {
        return { content: [{ type: "text", text: `❌ job_id를 찾을 수 없습니다: ${job_id}` }] };
      }

      const recentLogs = job.logs.slice(-5).join("\n");

      if (job.status === "running") {
        return {
          content: [{
            type: "text",
            text: `⏳ 작업 진행 중...\n\njob_id: ${job_id}\n\n최근 로그:\n${recentLogs}`,
          }],
        };
      }

      if (job.status === "error") {
        return {
          content: [{
            type: "text",
            text: `❌ 작업 실패\n\njob_id: ${job_id}\n오류: ${job.error}\n\n최근 로그:\n${recentLogs}`,
          }],
        };
      }

      return {
        content: [{ type: "text", text: job.result.text }],
      };
    }
  );

  return server;
}

app.post("/mcp", async (req, res) => {
  const transport = new StreamableHTTPServerTransport({ sessionIdGenerator: undefined });
  const server = createServer();
  await server.connect(transport);
  await transport.handleRequest(req, res, req.body);
  await server.close();
});

app.get("/health", (_, res) => res.json({ status: "ok", server: "front" }));

app.get("/jobs/:id", (req, res) => {
  const job = jobs.get(req.params.id);
  if (!job) return res.status(404).json({ error: "not found" });
  res.json({
    job_id: req.params.id,
    status: job.status,
    prompt: job.prompt,
    createdAt: job.createdAt,
    logs: job.logs,
    result: job.result,
    error: job.error,
  });
});

app.listen(5004, () => process.stdout.write("front MCP server running on :5004\n"));
